// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tora.proto

package com.example.grpc.protoclass;

public final class Tora {
  private Tora() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.grpc.protoclass.Req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string msg1 = 1;</code>
     */
    java.lang.String getMsg1();
    /**
     * <code>string msg1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsg1Bytes();

    /**
     * <code>string msg2 = 2;</code>
     */
    java.lang.String getMsg2();
    /**
     * <code>string msg2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsg2Bytes();

    /**
     * <code>string msg3 = 3;</code>
     */
    java.lang.String getMsg3();
    /**
     * <code>string msg3 = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsg3Bytes();

    /**
     * <code>int32 type = 4;</code>
     */
    int getType();
  }
  /**
   * Protobuf type {@code com.example.grpc.protoclass.Req}
   */
  public  static final class Req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.grpc.protoclass.Req)
      ReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Req.newBuilder() to construct.
    private Req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Req() {
      msg1_ = "";
      msg2_ = "";
      msg3_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msg1_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg2_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              msg3_ = s;
              break;
            }
            case 32: {

              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.protoclass.Tora.internal_static_com_example_grpc_protoclass_Req_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.protoclass.Tora.internal_static_com_example_grpc_protoclass_Req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.protoclass.Tora.Req.class, com.example.grpc.protoclass.Tora.Req.Builder.class);
    }

    public static final int MSG1_FIELD_NUMBER = 1;
    private volatile java.lang.Object msg1_;
    /**
     * <code>string msg1 = 1;</code>
     */
    public java.lang.String getMsg1() {
      java.lang.Object ref = msg1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg1_ = s;
        return s;
      }
    }
    /**
     * <code>string msg1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsg1Bytes() {
      java.lang.Object ref = msg1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG2_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg2_;
    /**
     * <code>string msg2 = 2;</code>
     */
    public java.lang.String getMsg2() {
      java.lang.Object ref = msg2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg2_ = s;
        return s;
      }
    }
    /**
     * <code>string msg2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsg2Bytes() {
      java.lang.Object ref = msg2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG3_FIELD_NUMBER = 3;
    private volatile java.lang.Object msg3_;
    /**
     * <code>string msg3 = 3;</code>
     */
    public java.lang.String getMsg3() {
      java.lang.Object ref = msg3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg3_ = s;
        return s;
      }
    }
    /**
     * <code>string msg3 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsg3Bytes() {
      java.lang.Object ref = msg3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>int32 type = 4;</code>
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsg1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msg1_);
      }
      if (!getMsg2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg2_);
      }
      if (!getMsg3Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg3_);
      }
      if (type_ != 0) {
        output.writeInt32(4, type_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsg1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msg1_);
      }
      if (!getMsg2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg2_);
      }
      if (!getMsg3Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg3_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.grpc.protoclass.Tora.Req)) {
        return super.equals(obj);
      }
      com.example.grpc.protoclass.Tora.Req other = (com.example.grpc.protoclass.Tora.Req) obj;

      boolean result = true;
      result = result && getMsg1()
          .equals(other.getMsg1());
      result = result && getMsg2()
          .equals(other.getMsg2());
      result = result && getMsg3()
          .equals(other.getMsg3());
      result = result && (getType()
          == other.getType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG1_FIELD_NUMBER;
      hash = (53 * hash) + getMsg1().hashCode();
      hash = (37 * hash) + MSG2_FIELD_NUMBER;
      hash = (53 * hash) + getMsg2().hashCode();
      hash = (37 * hash) + MSG3_FIELD_NUMBER;
      hash = (53 * hash) + getMsg3().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.grpc.protoclass.Tora.Req parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.protoclass.Tora.Req parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.protoclass.Tora.Req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.protoclass.Tora.Req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.protoclass.Tora.Req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.protoclass.Tora.Req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.protoclass.Tora.Req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.protoclass.Tora.Req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.protoclass.Tora.Req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.grpc.protoclass.Tora.Req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.protoclass.Tora.Req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.protoclass.Tora.Req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.grpc.protoclass.Tora.Req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.grpc.protoclass.Req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.grpc.protoclass.Req)
        com.example.grpc.protoclass.Tora.ReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.grpc.protoclass.Tora.internal_static_com_example_grpc_protoclass_Req_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.grpc.protoclass.Tora.internal_static_com_example_grpc_protoclass_Req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.grpc.protoclass.Tora.Req.class, com.example.grpc.protoclass.Tora.Req.Builder.class);
      }

      // Construct using com.example.grpc.protoclass.Tora.Req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msg1_ = "";

        msg2_ = "";

        msg3_ = "";

        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.grpc.protoclass.Tora.internal_static_com_example_grpc_protoclass_Req_descriptor;
      }

      public com.example.grpc.protoclass.Tora.Req getDefaultInstanceForType() {
        return com.example.grpc.protoclass.Tora.Req.getDefaultInstance();
      }

      public com.example.grpc.protoclass.Tora.Req build() {
        com.example.grpc.protoclass.Tora.Req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.grpc.protoclass.Tora.Req buildPartial() {
        com.example.grpc.protoclass.Tora.Req result = new com.example.grpc.protoclass.Tora.Req(this);
        result.msg1_ = msg1_;
        result.msg2_ = msg2_;
        result.msg3_ = msg3_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.grpc.protoclass.Tora.Req) {
          return mergeFrom((com.example.grpc.protoclass.Tora.Req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.grpc.protoclass.Tora.Req other) {
        if (other == com.example.grpc.protoclass.Tora.Req.getDefaultInstance()) return this;
        if (!other.getMsg1().isEmpty()) {
          msg1_ = other.msg1_;
          onChanged();
        }
        if (!other.getMsg2().isEmpty()) {
          msg2_ = other.msg2_;
          onChanged();
        }
        if (!other.getMsg3().isEmpty()) {
          msg3_ = other.msg3_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.grpc.protoclass.Tora.Req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.grpc.protoclass.Tora.Req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object msg1_ = "";
      /**
       * <code>string msg1 = 1;</code>
       */
      public java.lang.String getMsg1() {
        java.lang.Object ref = msg1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsg1Bytes() {
        java.lang.Object ref = msg1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg1 = 1;</code>
       */
      public Builder setMsg1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg1 = 1;</code>
       */
      public Builder clearMsg1() {
        
        msg1_ = getDefaultInstance().getMsg1();
        onChanged();
        return this;
      }
      /**
       * <code>string msg1 = 1;</code>
       */
      public Builder setMsg1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msg2_ = "";
      /**
       * <code>string msg2 = 2;</code>
       */
      public java.lang.String getMsg2() {
        java.lang.Object ref = msg2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsg2Bytes() {
        java.lang.Object ref = msg2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg2 = 2;</code>
       */
      public Builder setMsg2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg2 = 2;</code>
       */
      public Builder clearMsg2() {
        
        msg2_ = getDefaultInstance().getMsg2();
        onChanged();
        return this;
      }
      /**
       * <code>string msg2 = 2;</code>
       */
      public Builder setMsg2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msg3_ = "";
      /**
       * <code>string msg3 = 3;</code>
       */
      public java.lang.String getMsg3() {
        java.lang.Object ref = msg3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg3_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg3 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsg3Bytes() {
        java.lang.Object ref = msg3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg3 = 3;</code>
       */
      public Builder setMsg3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg3 = 3;</code>
       */
      public Builder clearMsg3() {
        
        msg3_ = getDefaultInstance().getMsg3();
        onChanged();
        return this;
      }
      /**
       * <code>string msg3 = 3;</code>
       */
      public Builder setMsg3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg3_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 4;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.grpc.protoclass.Req)
    }

    // @@protoc_insertion_point(class_scope:com.example.grpc.protoclass.Req)
    private static final com.example.grpc.protoclass.Tora.Req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.grpc.protoclass.Tora.Req();
    }

    public static com.example.grpc.protoclass.Tora.Req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Req>
        PARSER = new com.google.protobuf.AbstractParser<Req>() {
      public Req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Req> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Req> getParserForType() {
      return PARSER;
    }

    public com.example.grpc.protoclass.Tora.Req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.grpc.protoclass.Res)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>int32 stat = 2;</code>
     */
    int getStat();

    /**
     * <code>.com.example.grpc.protoclass.Req message = 3;</code>
     */
    boolean hasMessage();
    /**
     * <code>.com.example.grpc.protoclass.Req message = 3;</code>
     */
    com.example.grpc.protoclass.Tora.Req getMessage();
    /**
     * <code>.com.example.grpc.protoclass.Req message = 3;</code>
     */
    com.example.grpc.protoclass.Tora.ReqOrBuilder getMessageOrBuilder();
  }
  /**
   * Protobuf type {@code com.example.grpc.protoclass.Res}
   */
  public  static final class Res extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.grpc.protoclass.Res)
      ResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Res.newBuilder() to construct.
    private Res(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Res() {
      stat_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Res(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              stat_ = input.readInt32();
              break;
            }
            case 26: {
              com.example.grpc.protoclass.Tora.Req.Builder subBuilder = null;
              if (message_ != null) {
                subBuilder = message_.toBuilder();
              }
              message_ = input.readMessage(com.example.grpc.protoclass.Tora.Req.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(message_);
                message_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.protoclass.Tora.internal_static_com_example_grpc_protoclass_Res_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.protoclass.Tora.internal_static_com_example_grpc_protoclass_Res_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.protoclass.Tora.Res.class, com.example.grpc.protoclass.Tora.Res.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    public static final int STAT_FIELD_NUMBER = 2;
    private int stat_;
    /**
     * <code>int32 stat = 2;</code>
     */
    public int getStat() {
      return stat_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private com.example.grpc.protoclass.Tora.Req message_;
    /**
     * <code>.com.example.grpc.protoclass.Req message = 3;</code>
     */
    public boolean hasMessage() {
      return message_ != null;
    }
    /**
     * <code>.com.example.grpc.protoclass.Req message = 3;</code>
     */
    public com.example.grpc.protoclass.Tora.Req getMessage() {
      return message_ == null ? com.example.grpc.protoclass.Tora.Req.getDefaultInstance() : message_;
    }
    /**
     * <code>.com.example.grpc.protoclass.Req message = 3;</code>
     */
    public com.example.grpc.protoclass.Tora.ReqOrBuilder getMessageOrBuilder() {
      return getMessage();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != null) {
        output.writeMessage(1, getTimestamp());
      }
      if (stat_ != 0) {
        output.writeInt32(2, stat_);
      }
      if (message_ != null) {
        output.writeMessage(3, getMessage());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTimestamp());
      }
      if (stat_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, stat_);
      }
      if (message_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.grpc.protoclass.Tora.Res)) {
        return super.equals(obj);
      }
      com.example.grpc.protoclass.Tora.Res other = (com.example.grpc.protoclass.Tora.Res) obj;

      boolean result = true;
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && getTimestamp()
            .equals(other.getTimestamp());
      }
      result = result && (getStat()
          == other.getStat());
      result = result && (hasMessage() == other.hasMessage());
      if (hasMessage()) {
        result = result && getMessage()
            .equals(other.getMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (37 * hash) + STAT_FIELD_NUMBER;
      hash = (53 * hash) + getStat();
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.grpc.protoclass.Tora.Res parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.protoclass.Tora.Res parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.protoclass.Tora.Res parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.protoclass.Tora.Res parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.protoclass.Tora.Res parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.protoclass.Tora.Res parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.protoclass.Tora.Res parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.protoclass.Tora.Res parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.protoclass.Tora.Res parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.grpc.protoclass.Tora.Res parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.protoclass.Tora.Res parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.protoclass.Tora.Res parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.grpc.protoclass.Tora.Res prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.grpc.protoclass.Res}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.grpc.protoclass.Res)
        com.example.grpc.protoclass.Tora.ResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.grpc.protoclass.Tora.internal_static_com_example_grpc_protoclass_Res_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.grpc.protoclass.Tora.internal_static_com_example_grpc_protoclass_Res_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.grpc.protoclass.Tora.Res.class, com.example.grpc.protoclass.Tora.Res.Builder.class);
      }

      // Construct using com.example.grpc.protoclass.Tora.Res.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        stat_ = 0;

        if (messageBuilder_ == null) {
          message_ = null;
        } else {
          message_ = null;
          messageBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.grpc.protoclass.Tora.internal_static_com_example_grpc_protoclass_Res_descriptor;
      }

      public com.example.grpc.protoclass.Tora.Res getDefaultInstanceForType() {
        return com.example.grpc.protoclass.Tora.Res.getDefaultInstance();
      }

      public com.example.grpc.protoclass.Tora.Res build() {
        com.example.grpc.protoclass.Tora.Res result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.grpc.protoclass.Tora.Res buildPartial() {
        com.example.grpc.protoclass.Tora.Res result = new com.example.grpc.protoclass.Tora.Res(this);
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        result.stat_ = stat_;
        if (messageBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.grpc.protoclass.Tora.Res) {
          return mergeFrom((com.example.grpc.protoclass.Tora.Res)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.grpc.protoclass.Tora.Res other) {
        if (other == com.example.grpc.protoclass.Tora.Res.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (other.getStat() != 0) {
          setStat(other.getStat());
        }
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.grpc.protoclass.Tora.Res parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.grpc.protoclass.Tora.Res) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private int stat_ ;
      /**
       * <code>int32 stat = 2;</code>
       */
      public int getStat() {
        return stat_;
      }
      /**
       * <code>int32 stat = 2;</code>
       */
      public Builder setStat(int value) {
        
        stat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 stat = 2;</code>
       */
      public Builder clearStat() {
        
        stat_ = 0;
        onChanged();
        return this;
      }

      private com.example.grpc.protoclass.Tora.Req message_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.grpc.protoclass.Tora.Req, com.example.grpc.protoclass.Tora.Req.Builder, com.example.grpc.protoclass.Tora.ReqOrBuilder> messageBuilder_;
      /**
       * <code>.com.example.grpc.protoclass.Req message = 3;</code>
       */
      public boolean hasMessage() {
        return messageBuilder_ != null || message_ != null;
      }
      /**
       * <code>.com.example.grpc.protoclass.Req message = 3;</code>
       */
      public com.example.grpc.protoclass.Tora.Req getMessage() {
        if (messageBuilder_ == null) {
          return message_ == null ? com.example.grpc.protoclass.Tora.Req.getDefaultInstance() : message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.example.grpc.protoclass.Req message = 3;</code>
       */
      public Builder setMessage(com.example.grpc.protoclass.Tora.Req value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.example.grpc.protoclass.Req message = 3;</code>
       */
      public Builder setMessage(
          com.example.grpc.protoclass.Tora.Req.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.example.grpc.protoclass.Req message = 3;</code>
       */
      public Builder mergeMessage(com.example.grpc.protoclass.Tora.Req value) {
        if (messageBuilder_ == null) {
          if (message_ != null) {
            message_ =
              com.example.grpc.protoclass.Tora.Req.newBuilder(message_).mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          messageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.example.grpc.protoclass.Req message = 3;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = null;
          onChanged();
        } else {
          message_ = null;
          messageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.example.grpc.protoclass.Req message = 3;</code>
       */
      public com.example.grpc.protoclass.Tora.Req.Builder getMessageBuilder() {
        
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.example.grpc.protoclass.Req message = 3;</code>
       */
      public com.example.grpc.protoclass.Tora.ReqOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_ == null ?
              com.example.grpc.protoclass.Tora.Req.getDefaultInstance() : message_;
        }
      }
      /**
       * <code>.com.example.grpc.protoclass.Req message = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.grpc.protoclass.Tora.Req, com.example.grpc.protoclass.Tora.Req.Builder, com.example.grpc.protoclass.Tora.ReqOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.grpc.protoclass.Tora.Req, com.example.grpc.protoclass.Tora.Req.Builder, com.example.grpc.protoclass.Tora.ReqOrBuilder>(
                  getMessage(),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.grpc.protoclass.Res)
    }

    // @@protoc_insertion_point(class_scope:com.example.grpc.protoclass.Res)
    private static final com.example.grpc.protoclass.Tora.Res DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.grpc.protoclass.Tora.Res();
    }

    public static com.example.grpc.protoclass.Tora.Res getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Res>
        PARSER = new com.google.protobuf.AbstractParser<Res>() {
      public Res parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Res(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Res> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Res> getParserForType() {
      return PARSER;
    }

    public com.example.grpc.protoclass.Tora.Res getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_protoclass_Req_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_protoclass_Req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_protoclass_Res_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_protoclass_Res_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTora.proto\022\033com.example.grpc.protoclas" +
      "s\032\037google/protobuf/timestamp.proto\"=\n\003Re" +
      "q\022\014\n\004msg1\030\001 \001(\t\022\014\n\004msg2\030\002 \001(\t\022\014\n\004msg3\030\003 " +
      "\001(\t\022\014\n\004type\030\004 \001(\005\"u\n\003Res\022-\n\ttimestamp\030\001 " +
      "\001(\0132\032.google.protobuf.Timestamp\022\014\n\004stat\030" +
      "\002 \001(\005\0221\n\007message\030\003 \001(\0132 .com.example.grp" +
      "c.protoclass.Req2e\n\013ToraService\022V\n\014sendM" +
      "essageA\022 .com.example.grpc.protoclass.Re" +
      "q\032 .com.example.grpc.protoclass.Res(\0010\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_example_grpc_protoclass_Req_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_protoclass_Req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_protoclass_Req_descriptor,
        new java.lang.String[] { "Msg1", "Msg2", "Msg3", "Type", });
    internal_static_com_example_grpc_protoclass_Res_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_protoclass_Res_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_protoclass_Res_descriptor,
        new java.lang.String[] { "Timestamp", "Stat", "Message", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
